### ISSUE TITLE
Issues with wait resolving

### ISSUE THREAD

**Issue by mathatan** [PuSuEngine/jspusu#2]
There's a couple of issues. First `_waiter` can be overwritten if there's multiple wait request from different sources. This can result in some of the deferreds never being resolved. Also if the timeout triggers it's still possible that the waiter callback tries to resolve the deferred. It's unlikely that it would break anything, but it's probably a good practice to check if the deferred has been rejected before trying to resolve it.

https://github.com/PuSuEngine/jspusu/blob/master/src/pusu.ts#L195

**Comment by lietu** [comment]
https://github.com/PuSuEngine/jspusu/commit/9fb983e4c92ff04f4ef4e8028823613fc5805f49 should fix the waiting issues
