### ISSUE TITLE
There can only be one subscriber per channel

### ISSUE THREAD

**Issue by mathatan** [PuSuEngine/jspusu#3]
It would be preferable to be able to subscribe multiple listeners per channel. It's always possible that the socket connection is used from multiple places in which case listener could be overwritten.

https://github.com/PuSuEngine/jspusu/blob/master/src/pusu.ts#L159

**Comment by lietu** [comment]
Fixed by https://github.com/PuSuEngine/jspusu/commit/9fb983e4c92ff04f4ef4e8028823613fc5805f49
